name: Check data assets

on:
  workflow_dispatch:

env:
  AZURE_RESOURCE_GROUP: 'rg-testdiab'
  AZURE_WORKSPACE: 'mlw-testdiab'
  AZURE_SUBSCRIPTION: 'd54efa0b-8643-493a-abce-511f6d3fc00b'

jobs:
  check_assets:
    name: Check assets
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Check out repo
        uses: actions/checkout@main

      - name: Install az ml extension
        run: az extension add -n ml -y

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}

      - name: Check variables
        run: az ml data list --workspace-name $AZURE_WORKSPACE --resource-group $AZURE_RESOURCE_GROUP -o table
