name: Stoponpull

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  lint:
    name: Lint code with Flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8

      - name: Run Flake8
        run: |
          flake8 .

  tests:
    name: Run unit tests with Pytest
    runs-on: ubuntu-latest
    needs: lint   # optional: run tests only if lint passes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run Pytest
        run: |
          pytest tests/

  experimentation:
    name: "Experimentation phase"
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Submit experiment job
        run: |
          az ml job create \
            --file src/job.yml \
            --resource-group "$AZURE_RESOURCE_GROUP" \
            --workspace-name "$AZURE_WORKSPACE" \
            --set inputs.training_data=azureml:diabetes-dev-folder

  
  production:
    name: "Production phase"
    runs-on: ubuntu-latest
    needs: experimentation
    if: ${{ needs.A.result == 'success' }}
    steps:
      - name: "training on production data"
        run: |
          az ml job create \
            --file src/job.yml \
            --resource-group $AZURE_RESOURCE_GROUP \
            --workspace-name $AZURE_WORKSPACE \
            --set inputs.training_data=azureml:diabetes-prod-folder
