name: Stoponpull

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AZURE_RESOURCE_GROUP: 'rg-testdiab'
  AZURE_WORKSPACE: 'mlw-testdiab'
  AZURE_SUBSCRIPTION: 'd54efa0b-8643-493a-abce-511f6d3fc00b'

jobs:
  lint:
    name: Lint code with Flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8

      - name: Run Flake8
        run: |
          flake8 .

  tests:
    name: Run unit tests with Pytest
    runs-on: ubuntu-latest
    needs: lint   # optional: run tests only if lint passes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run Pytest
        run: |
          pytest tests/

  dataset_creation:
    name: "Create datasets"
    runs-on: ubuntu-latest
    environment: experimentation
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Install az ml extension
        run: az extension add -n ml -y
        
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS_DEV}}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Enable ML auto extension auto-install
        run: az config set extension.dynamic_install_allow_preview=true

      - name: Dataset for experimentation
        run: |
          az ml data create --name diabetes-exp-folder \
          --type uri_folder \
          --path ./experimentation/data \
          --workspace-name $AZURE_WORKSPACE \
          --resource-group $AZURE_RESOURCE_GROUP

      - name: Dataset for production 
        run: |
          az ml data create --name diabetes-dev-folder \
          --type uri_folder \
          --path ./production/data \
          --workspace-name $AZURE_WORKSPACE \
          --resource-group $AZURE_RESOURCE_GROUP

  experimentation:
    name: "Experimentation phase"
    runs-on: ubuntu-latest
    environment: experimentation
    needs: dataset_creation        
    if: ${{ needs.dataset_creation.result == 'success' }}
    steps:
      - name: Debug environment variables
        run: |
          echo "RG = [$AZURE_RESOURCE_GROUP]"
          echo "RG2 = ${{vars.AZURE_RESOURCE_GROUP}}"
          echo "WS = [$AZURE_WORKSPACE]"
          echo "Subscription = [$AZURE_SUBSCRIPTION]"
          az account show || echo "No Azure login"

      - name: Checkout repository
        uses: actions/checkout@main

      - name: Install az ml extension
        run: az extension add -n ml -y
        
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS_DEV}}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Enable ML auto extension auto-install
        run: az config set extension.dynamic_install_allow_preview=true

      - name: training on experiment data
        run: |
          az ml job create \
            --file src/job.yml \
            --resource-group $AZURE_RESOURCE_GROUP \
            --workspace-name $AZURE_WORKSPACE \
            --set inputs.training_data=azureml:diabetes-exp-folder
  
  production:
    name: "Production phase"
    runs-on: ubuntu-latest
    environment: production
    needs: experimentation
    if: ${{ needs.experimentation.result == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS_PROD}}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Enable ML auto extension auto-install
        run: az config set extension.dynamic_install_allow_preview=true

      - name: training on production data
        run: |
          az ml job create \
            --file src/job.yml \
            --resource-group "$AZURE_RESOURCE_GROUP" \
            --workspace-name $AZURE_WORKSPACE \
            --set inputs.training_data=azureml:diabetes-prod-folder
